// <auto-generated />
namespace Server_WEB_Programming.Lab2.Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Altered_BookOrder_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Altered_BookOrder_table));
        
        string IMigrationMetadata.Id
        {
            get { return "201910080931295_Altered_BookOrder_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
